import { PrismaClient } from '@prisma/client';
import { app } from 'electron';
import path from 'path';

import fs from 'fs';

// Get the user data path where the database will be stored
const isDev = process.env.NODE_ENV === 'development' || !app.isPackaged;

// In development, use the prisma/dev.db generated by Prisma CLI
const devDbPath = path.join(process.cwd(), 'prisma', 'dev.db');

// In production, we must copy the bundled dev.db to userData on first launch
const prodDbPath = path.join(app.getPath('userData'), 'bengkelpro.db');

if (!isDev) {
  // If we're packaged and the user DB doesn't exist yet, copy our baseline DB over
  if (!fs.existsSync(prodDbPath)) {
    // electron-builder will put prisma/dev.db in the app.asar.unpacked directory (as configured in package.json)
    const bundledDbPath = path.join(process.resourcesPath, 'app.asar.unpacked', 'prisma', 'dev.db');
    if (fs.existsSync(bundledDbPath)) {
      fs.copyFileSync(bundledDbPath, prodDbPath);
    }
  }
}

const dbPath = isDev ? devDbPath : prodDbPath;

export const prisma = new PrismaClient({
  datasources: {
    db: {
      url: `file:${dbPath}`,
    },
  },
});
