import { PrismaClient } from '@prisma/client';
import { app } from 'electron';
import path from 'path';

import fs from 'fs';

// Get the user data path where the database will be stored
const isDev = process.env.NODE_ENV === 'development' || !app.isPackaged;

// In development, use the prisma/dev.db generated by Prisma CLI
const devDbPath = path.join(process.cwd(), 'prisma', 'dev.db');

// In production, we must copy the bundled dev.db to userData on first launch
const prodDbPath = path.join(app.getPath('userData'), 'bengkelpro.db');

if (!isDev) {
  // If we're packaged and the user DB doesn't exist yet, copy our baseline DB over
  if (!fs.existsSync(prodDbPath)) {
    // electron-builder extraResources puts prisma in process.resourcesPath/prisma
    const bundledDbPath = path.join(process.resourcesPath, 'prisma', 'dev.db');
    if (fs.existsSync(bundledDbPath)) {
      const prodDbDir = path.dirname(prodDbPath);
      if (!fs.existsSync(prodDbDir)) {
        fs.mkdirSync(prodDbDir, { recursive: true });
      }
      fs.copyFileSync(bundledDbPath, prodDbPath);
    }
  }
}

export const dbPath = isDev ? devDbPath : prodDbPath;

if (!isDev) {
  // Set the Prisma engine path to the one we copied into resources/prisma
  process.env.PRISMA_QUERY_ENGINE_LIBRARY = path.join(process.resourcesPath, 'prisma', 'query_engine-windows.dll.node');
}

export const prisma = new PrismaClient({
  datasources: {
    db: {
      url: `file:${dbPath}`,
    },
  },
});
